print('='*12, 'Primerio e Último nome da pessoa', '='*12)
nome = str(input('Digite seu nome completo: ')).strip()
print(f'Muito prazer em te conhecer {nome}!')
dividido = nome.split()
print('Seu primeiro nome é {}'.format(dividido[0]))
print('Seu último nome é {}'.format(dividido[len(dividido)-1]))
